### ISSUE TITLE
Publish package on packagist.org?

### ISSUE THREAD

**Issue by mlocati** [ounziw/Free-Map#5]
What about adding this package to https://packagist.org ?

That way, installing it in a composer-based installation would be as easy as running

```
composer require ounziw/ounziw_osm
```

Adding a package to packagist can be done with these simple steps:

1. go to https://packagist.org and click `Sign in` &rarr; `Use GitHub` to log in
2. click the `Submit` button and specify the URL of this repository ( `https://github.com/ounziw/Free-Map` )

**Comment by ounziw** [comment]
Hello,

I registered packagist and submit my addon.
https://packagist.org/packages/ounziw/ounziw_osm

**Comment by mlocati** [comment]
Great, thank you!

One more thing though: packagist (and composer) can't extract the package version from the Concrete controller.php file (it's a Concrete-specific stuff).

In order to tell packagist/composer the version of the package, we need to use git tags.

Also, we should switch to [semver](https://semver.org/) for versions... In summary:
- versions have always 3 numbers (`MajorVersion`.`MinorVersion`.`PatchVersion`)
- when we publish a new version that only fixes bugs, we increase `PatchVersion`
- when we publish a new version that adds new features, we increase `MinorVersion`
- when we publish a new version that introduces breaking changes, we increase `MajorVersion`

So, what about tagging the last published version (which is at commit b70708cd000b06f312206f97c7a5994c7bddfd7e)? It'd be as easy as:
- creating a tag with
   ```
   git tag 2.1.0 b70708cd000b06f312206f97c7a5994c7bddfd7e
   ```
- push the tag to this GitHub repository with
   ```
   git push --tags
   ```

**Comment by ounziw** [comment]
I added a tag 2.1.0.

https://github.com/ounziw/Free-Map/releases/tag/2.1.0

**Comment by mlocati** [comment]
Thanks!
